name: Run Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # puedes elegir la versión de Node.js que prefieras

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npx cypress run
